version: "3.7"

services:
#   kratos-migrate:
#     image: oryd/kratos:v0.10.1
#     depends_on:
#       - postgresd
#     environment:
#       - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
#       # - DSN=postgres://postgres:Welcome@1_0@postgres-kratos:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
#     volumes:
#       - type: volume
#         source: kratos-postgres
#         target: /var/lib/postgres
#         read_only: false
#       - type: bind
#         source: ./kratos
#         target: /etc/config/kratos
#     command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
#     restart: on-failure
#     networks:
#       - intranet

#   kratos:
#     depends_on:
#       - kratos-migrate
#     image: oryd/kratos:v0.10.1
#     ports:
#       - "4433:4433" # public
#       - "4434:4434" # admin
#       - "50002:50002"
#       - "3500:3500"
#     restart: unless-stopped
#     environment:
#       - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
#       # - DSN=postgres://postgres:Welcome@1_0@postgres-kratos:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
#       - LOG_LEVEL=trace
#     command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
#     volumes:
#       - type: volume
#         source: kratos-postgres
#         target: /var/lib/postgres
#         read_only: false
#       - type: bind
#         source: ./kratos
#         target: /etc/config/kratos
#     networks:
#       - intranet

#   mailslurper:
#     image: oryd/mailslurper:latest-smtps
#     ports:
#       - "4436:4436"
#       - "4437:4437"
#     networks:
#       - intranet
#   postgresd:
#     image: postgres:11.5-alpine
#     environment:
#       - POSTGRES_USER=kratos
#       - POSTGRES_PASSWORD=secret
#       - POSTGRES_DB=kratos
#     ports:
#       - "5432:5432"
#     volumes:
#       - kratos-postgres:/var/lib/postgres
#     networks:
#       - intranet
# networks:
#   intranet:

# volumes:
#   kratos-postgres:
  postgres-kratos:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet
  kratos-migrate:
    image: oryd/kratos:v0.10.1
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
  kratos:
    image: oryd/kratos:v0.10.1
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - '4433:4433'
      - '4434:4434'
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:latest
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://192.168.0.6:4433/
    networks:
      - intranet
    # ports:
    #   - "4455:4200"
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
networks:
  intranet:
